default_context:
  project_name: '{{ project.project_name }}'
  project_slug: '{{ project.project_slug }}'
  domain_main: '{{ project.domain_main }}'
  domain_staging: '{{ project.domain_staging }}'
  docker_swarm_stack_name_main: '{{ project.docker_swarm_stack_name_main }}'
  docker_swarm_stack_name_staging: '{{ project.docker_swarm_stack_name_staging }}'
  secret_key: '{{ project.secret_key }}'
  first_superuser: '{{ project.first_superuser }}'
  first_superuser_password: '{{ project.first_superuser_password }}'
  backend_cors_origins: '{{ project.backend_cors_origins }}'
  smtp_port: '{{ project.smtp_port }}'
  smtp_host: '{{ project.smtp_host }}'
  smtp_user: '{{ project.smtp_user }}'
  smtp_password: '{{ project.smtp_password }}'
  smtp_emails_from_email: '{{ project.smtp_emails_from_email }}'
  postgres_password: '{{ project.postgres_password }}'
  pgadmin_default_user: '{{ project.pgadmin_default_user }}'
  pgadmin_default_user_password: '{{ project.pgadmin_default_user_password }}'
  traefik_constraint_tag: '{{ project.traefik_constraint_tag }}'
  traefik_constraint_tag_staging: '{{ project.traefik_constraint_tag_staging }}'
  traefik_public_constraint_tag: '{{ project.traefik_public_constraint_tag }}'
  flower_auth: '{{ project.flower_auth }}'
  sentry_dsn: '{{ project.sentry_dsn }}'
  docker_image_prefix: '{{ project.docker_image_prefix }}'
  docker_image_backend: '{{ project.docker_image_backend }}'
  docker_image_celeryworker: '{{ project.docker_image_celeryworker }}'
  docker_image_frontend: '{{ project.docker_image_frontend }}'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
